### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xsuchy** [laabicz/HomeLESS#1]
Can you please specify under which license is this code available?

**Comment by laabicz** [comment]
Zdravím,
nahrál jsem neoficiální (provedu je¹tì pár malých úprav) verzi HomeLESS Hit
Analyzer 1.1b s doplòenou licencí. Je takto uvedená licence v poøádku nebo
jí mám je¹tì upravit (jak)

S pozdravem

Laabicz

2013/9/18 Miroslav Suchý notifications@github.com

**Comment by xsuchy** [comment]
Ano, ted je to zrejme. Dekuji.
