### ISSUE TITLE
What version of which library is needed to run this

### ISSUE THREAD

**Issue by sampoz** [laabicz/HomeLESS#2]
Hi!

I Am trying to develop this further in order to post the scores online as soon as the system registers them, but I can't get the the project running in processing, as it seems to require specific versions of the libraries. The winbundle version runs fine. The error is:

"The class guicomponents.GTextField is incompatible with Processing 2.0.
A library (or other code) is using registerKeyEvent() which is no longer available." 

So It seems that guicomponents  does not work with Processing 2.\* I am running processing 2.2.1.

**Comment by laabicz** [comment]
Hi,
you have to try older version of Processing (2.0.3) and library
(attachment). But better option is wait for new version. Where will be
functionality which can handle this problem :) .

Best Regards

Laabicz

**Comment by sampoz** [comment]
Great, thanks! I'll try that shortly, is the library attached in the windows bundle or somewhere else?

**Comment by sampoz** [comment]
Managed to solve this with your help, using Processing 2.0.3 and then downloading the libraries from the internet helped, Thanks for the help and for this awesome OpenSource Project :)
