### ISSUE TITLE
Unable to Hear Sound/s while Hitting Target

### ISSUE THREAD

**Issue by BhagyodayPatil** [laabicz/HomeLESS#4]
I am not able to get any sound while shooting the Target. i.e GUN SHOT (default_gunshot.mp3) is not loading. Rest of the application is running fine. But NO Sounds.

Please can someone help me with this.

**Comment by laabicz** [comment]
Hi, I'm sorry for my late response. The sound is not supported in 1.2b version. I' sorry.
